In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import files
uploaded = files.upload()

Saving breast-cancer.csv to breast-cancer.csv

In [3]:
df = pd.read_csv("breast-cancer.csv")

In [4]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [5]:
df.shape

(569, 32)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB

In [7]:
df.isnull().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [8]:
df = df.drop("id", axis=1)

In [9]:
df["diagnosis"] = df["diagnosis"].map({"M": 1, "B": 0})

In [10]:
X = df.drop("diagnosis", axis=1)
y = df["diagnosis"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [11]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_validate

pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(random_state=42))
])

scores = cross_validate(
    pipe,
    X_train,
    y_train,
    cv=5,
    scoring=["accuracy","precision","recall","f1"]
)

print("===== Logistic Regression =====")

print("\nAccuracy")
for i, score in enumerate(scores["test_accuracy"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_accuracy"].mean())

print("\nPrecision")
for i, score in enumerate(scores["test_precision"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_precision"].mean())

print("\nRecall")
for i, score in enumerate(scores["test_recall"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_recall"].mean())

print("\nF1 Score")
for i, score in enumerate(scores["test_f1"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_f1"].mean())

===== Logistic Regression =====

Accuracy
Fold 1: 0.9670
Fold 2: 0.9890
Fold 3: 0.9560
Fold 4: 0.9780
Fold 5: 0.9670
Average: 0.9714285714285715

Precision
Fold 1: 1.0000
Fold 2: 0.9714
Fold 3: 1.0000
Fold 4: 0.9706
Fold 5: 0.9429
Average: 0.9769747899159664

Recall
Fold 1: 0.9118
Fold 2: 1.0000
Fold 3: 0.8824
Fold 4: 0.9706
Fold 5: 0.9706
Average: 0.9470588235294117

F1 Score
Fold 1: 0.9538
Fold 2: 0.9855
Fold 3: 0.9375
Fold 4: 0.9706
Fold 5: 0.9565
Average: 0.9607926749295036

In [12]:
from sklearn.tree import DecisionTreeClassifier

pipe = Pipeline([
    ("model", DecisionTreeClassifier(random_state=42))
])

scores = cross_validate(
    pipe,
    X_train,
    y_train,
    cv=5,
    scoring=["accuracy","precision","recall","f1"]
)

print("===== Decision Tree =====")

print("\nAccuracy")
for i, score in enumerate(scores["test_accuracy"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_accuracy"].mean())

print("\nPrecision")
for i, score in enumerate(scores["test_precision"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_precision"].mean())

print("\nRecall")
for i, score in enumerate(scores["test_recall"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_recall"].mean())

print("\nF1 Score")
for i, score in enumerate(scores["test_f1"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_f1"].mean())

===== Decision Tree =====

Accuracy
Fold 1: 0.9670
Fold 2: 0.9560
Fold 3: 0.9121
Fold 4: 0.9341
Fold 5: 0.8901
Average: 0.9318681318681318

Precision
Fold 1: 0.9697
Fold 2: 0.9167
Fold 3: 0.9333
Fold 4: 0.8889
Fold 5: 0.8333
Average: 0.9083838383838383

Recall
Fold 1: 0.9412
Fold 2: 0.9706
Fold 3: 0.8235
Fold 4: 0.9412
Fold 5: 0.8824
Average: 0.9117647058823529

F1 Score
Fold 1: 0.9552
Fold 2: 0.9429
Fold 3: 0.8750
Fold 4: 0.9143
Fold 5: 0.8571
Average: 0.9089019189765457

In [13]:
from sklearn.ensemble import RandomForestClassifier

pipe = Pipeline([
    ("model", RandomForestClassifier(random_state=42))
])

scores = cross_validate(
    pipe,
    X_train,
    y_train,
    cv=5,
    scoring=["accuracy","precision","recall","f1"]
)

print("===== Random Forest =====")

print("\nAccuracy")
for i, score in enumerate(scores["test_accuracy"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_accuracy"].mean())

print("\nPrecision")
for i, score in enumerate(scores["test_precision"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_precision"].mean())

print("\nRecall")
for i, score in enumerate(scores["test_recall"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_recall"].mean())

print("\nF1 Score")
for i, score in enumerate(scores["test_f1"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_f1"].mean())

===== Random Forest =====

Accuracy
Fold 1: 1.0000
Fold 2: 0.9890
Fold 3: 0.9341
Fold 4: 0.9780
Fold 5: 0.9121
Average: 0.9626373626373628

Precision
Fold 1: 1.0000
Fold 2: 1.0000
Fold 3: 0.9375
Fold 4: 0.9706
Fold 5: 0.8611
Average: 0.9538398692810457

Recall
Fold 1: 1.0000
Fold 2: 0.9706
Fold 3: 0.8824
Fold 4: 0.9706
Fold 5: 0.9118
Average: 0.9470588235294117

F1 Score
Fold 1: 1.0000
Fold 2: 0.9851
Fold 3: 0.9091
Fold 4: 0.9706
Fold 5: 0.8857
Average: 0.9500936113929968

In [14]:
from sklearn.svm import SVC

pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("model", SVC())
])

scores = cross_validate(
    pipe,
    X_train,
    y_train,
    cv=5,
    scoring=["accuracy","precision","recall","f1"]
)

print("===== SVM =====")

print("\nAccuracy")
for i, score in enumerate(scores["test_accuracy"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_accuracy"].mean())

print("\nPrecision")
for i, score in enumerate(scores["test_precision"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_precision"].mean())

print("\nRecall")
for i, score in enumerate(scores["test_recall"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_recall"].mean())

print("\nF1 Score")
for i, score in enumerate(scores["test_f1"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_f1"].mean())

===== SVM =====

Accuracy
Fold 1: 0.9670
Fold 2: 1.0000
Fold 3: 0.9670
Fold 4: 0.9670
Fold 5: 0.9670
Average: 0.9736263736263737

Precision
Fold 1: 1.0000
Fold 2: 1.0000
Fold 3: 1.0000
Fold 4: 0.9429
Fold 5: 0.9429
Average: 0.9771428571428572

Recall
Fold 1: 0.9118
Fold 2: 1.0000
Fold 3: 0.9118
Fold 4: 0.9706
Fold 5: 0.9706
Average: 0.9529411764705882

F1 Score
Fold 1: 0.9538
Fold 2: 1.0000
Fold 3: 0.9538
Fold 4: 0.9565
Fold 5: 0.9565
Average: 0.9641471571906355